### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by yemlahi** [jhuckaby/Effect-Games#1]
Hello everybody,

I have tried to install effect games, but I can't find the file "index.html" in order to use effect games from a server, So i've treid to create a file "index.html" but it doesn't work. If there is anyone who has a solution to this problem please don't tell me,

thanks in advance.

**Comment by jhuckaby** [comment]
Hey yemlahl,

Sorry for the confusion.  It looks like I missed something in the installation docs.  Effect uses its own custom HTML template system called PSP (Perl Server Pages), which is basically just Perl mixed in with HTML, and the base "index.html" file you were looking for is actually named "index.psp.html".  It is in the source tree here:

https://github.com/jhuckaby/Effect-Games/blob/master/htdocs/index.psp.html

Now, this file should automatically be loaded if you don't specify a filename on the URL.  But it obviously isn't for you, so I believe the problem is that you didn't use the provided Apache "httpd.conf" file, but instead used your own.  No problem, but unfortunately I didn't write complete instructions for doing so.  Here is what you need to know (and I am updating the installation guide with this info as well).

Here is the recommended httpd.conf file we reference:

http://www.effectgames.com/install/httpd.conf

If you choose to use your own, there are a few key things you need to make sure you have.  First, make sure you activate the mod_perl module:

``` apache
LoadModule perl_module modules/mod_perl.so
```

And most importantly of all, remember to include the "/effect/conf/apache.conf" file inside the httpd.conf file, which loads the Effect Engine at Apache startup.  This is what I assume is missing from your Apache config:

``` apache
Include /effect/conf/apache.conf
```

After you make those changes, try stopping and starting Apache and try hitting the base URL again.  Make sure you keep a close eye on your Apache Error Log and the Effect Debug log (/logs/effect/debug.log).

Thanks for letting us know about this!
- Joe

**Comment by yemlahi** [comment]
Thank you for answering my question, I have done all the configurations you adviced me to do but when I open the file "index.psp.html" I get this page :

set_ttl( 'ViewTTL' ); $self->header_out( 'Vary', 'User-Agent' ); ?>
{config}->{Strings}->{MainSlideshow}->{Slide}->[0]->{Text}; ?>
Search:  
Developer Account
Documentation
Loading...
Tutorials
Loading...
Tools
Placeholder Generator
Plugins
Loading...
Feeds
Dev Blog RSS
Community Blog RSS
Support
FAQ
Contact Us
Report a Bug

Copyright © 2005 - 2011 Effect Games
About Effect Games
{config}->{GoogAnalID} ? ("\n") : ''; ?>  

So if there are other changes to do, please tell me. Thnak you.

**Comment by jhuckaby** [comment]
Hmm, that's odd.  It's showing you the source of the page instead of the page itself (you can see the Perl code intermixed with the HTML, but it isn't executing the code).  So it looks like the Effect engine is not loaded in Apache, or is not activating for some reason.

The first thing I would do is look at your Apache Error Log, and make sure there weren't any errors on startup.  It could be that there is some mod_perl error that you aren't seeing on the console.

The second thing I would do is look at the Effect Debug Log (/logs/effect/debug.log) and make sure it contains information about starting up, and no errors.  You can use a "tail -f" command in Unix to watch this log live, and make sure it displays information as you request a page.  If not, the engine isn't loaded in Apache.

Sorry you are having problems with it.  Best of luck!
- Joe

**Comment by yemlahi** [comment]
Ok, and I'm using Windows and not Unix so do you think this can be a problem?

**Comment by jhuckaby** [comment]
Oh dear.  Yes, that is the problem.  It will not work on Windows.  Ever.  Sorry.

**Comment by yemlahi** [comment]
Ok thanks, I'm so happy because I can find the solution to the problem and
so Ican use Effect games for fun.

2011/7/4 jhuckaby <
reply@reply.github.com>

> Oh dear.  Yes, that is the problem.  It will not work on Windows.  Ever.
>  Sorry.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jhuckaby/Effect-Games/issues/1#issuecomment-1498711

## 

## 

EFREI P2012 - Ecole d'Ingnieur des Technologies de l'Information et
de la Communication
M1 - Ingnierie Logicielle
